### ISSUE TITLE
Visual Studio requis pour lancer / builder l'extension ?

### ISSUE THREAD

**Issue by Clemzd** [dunglas/vaccin.click#78]
Hello,

Je souhaites lancer ou builder l'extension en local mais j'ai cette erreur.

Visual Studio est requis pour lancer / builder l'extension ?

![image](https://user-images.githubusercontent.com/4448250/126451512-a5657091-4cdd-4456-ac70-8fba126a6d93.png)

**Comment by Clemzd** [comment]
Cela dit, ça fonctionne quand même donc j'ai l'impression que c'est un faux positif

**Comment by julienw** [comment]
Lorsqu'on installe des dépendances, il arrive que certaines dépendances veulent être compilées. Mais si ça échoue pas au final, je pense que c'est "npx" qui essaie de vérifier des trucs à l'avance, mais qu'on n'en a pas besoin pour nos dépendances...

Tu n'as rien d'autre après ça ? Peux-tu copier l'ensemble du texte ? (entre \``` pour pouvoir le mettre en "preformatté").

**Comment by Clemzd** [comment]
yes je vois

```
c.anonym@anonym MINGW64 /c/Workspaces/vaccin.click (main)
$ npx web-ext run
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:326:5)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\anonym\AppData\Roaming\npm-cache\_npx\6588\node_modules\web-ext\node_modules\dtrace-provider
```

**Comment by julienw** [comment]
OK, on dirait que ça vient de https://www.npmjs.com/package/dtrace-provider du coup. D'après leur README ça ne fonctionne pas pour Windows (et autres plates-formes) et ils fournissent un stub pour celles-ci, ainsi que là où la compilation échoue.

Donc je pense que ce n'est pas un souci pour nous.

Je me demande s'il faudrait reporter à https://github.com/mozilla/web-ext/...

**Comment by julienw** [comment]
Merci pour le rapport !
